### ISSUE TITLE
Fix CarTelemetryData parser

### ISSUE THREAD

**Issue by msansoni** [race-hub/f1-game-udp-parser#2]
@jonybur what's the issue with the parser for this packet at the moment?

**Comment by jonybur** [comment]
@msansoni It appears that the parser is outputting wrong information; for example when running the tests it shows that instead of outputting tyresPressure ```21.5, 21.5, 23, 23```; it outputs ```7.16328080420046e-39, 8.357159069835918e-39, 8.081646976168087e-39, 1.2611686178923354e-43```
The same happens with a number of different values, DRS should be a binary value (0 = off, 1 = on) but it outputs `226`.

**Comment by msansoni** [comment]
The benefits of testing! Thanks for spotting, hadn't included the m_brake field in the packet structure on the rust parser.

**Comment by jonybur** [comment]
No problem. I made a quick PR that fixes the build (just needed to add m_brake to the CarTelemetryData struct, and I also reenabled the test for that parser).
We could use a tool like Travis to check for the build & tests passing before allowing a merge as well.

**Comment by msansoni** [comment]
I've updated the TravisCI settings for the repo move. We just need to update the travis config to run the tests on commit now.

**Comment by jonybur** [comment]
Great! All is looking good from my end. Would you like to discuss visualisation?
