### ISSUE TITLE
Replace travis ci with github actions for packaging and release

### ISSUE THREAD

**Issue by msansoni** [race-hub/f1-game-udp-parser#8]
With GH acquiring NPM it would be logical for us to complete all the actions (testing and packaging) on GH ready for direct release onto NPM

**Comment by msansoni** [comment]
@jonybur please can you describe the steps you complete to package the TypeScript? Wanting to replicate it in the GH action.

**Comment by jonybur** [comment]
Hey @msansoni , you can package the TS by running
`$ npm run build` (deletes build folder, compiles TypeScript)
`$ npm pack` (generates a .tgz)
This wouldn't include the steps required to build the Rust part of the module (`$ npm run install`)
